name: CICD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.zip'
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: clean repo, execute py, commit
        run: |
          if [ -d "kodi20/zips" ]; then
            rm -rf kodi20/zips
          fi

          # Remove any file matching the pattern "chobe-*.zip"
          for file in chobe-*.zip; do
            rm "$file"
          done

          python _repo_generator.py

          # Move the generated .zip file with the dynamic version in the filename
          mv "kodi20/zips/chobe/chobe-*.zip" .
          
          # Get the name of the moved file
          moved_file=$(find . -name "chobe-*.zip" -type f)

          git config --global user.email "actions@github.com"
          git config --global user.name "action[bot]"
          git add --all
          git commit -m "Release"

          # Optionally, you can echo the moved file for debugging purposes
          echo "Moved file: $moved_file"

      - name: Pushing to the protected branch 'main'
        id: push-to-protected
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: main