name: CICD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: clean repo, execute py, 
        run: |
          rm -rf kodi20/zips
          rm tmptorm
          python _repo_generator.py
          mv kodi20/zips/chobe/chobe-0.0.1.zip .
          git config --global user.email "actions@github.com"
          git config --global user.name "action[bot]"
          git add --all
          git commit -m "Release"

      - name: Pushing to the protected branch 'main'
        id: push-to-protected
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: main